[tool.poetry]
name = "luminara"
version = "0.1.0"
description = ""
authors = ["Syunn"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.13,<3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
